### ISSUE TITLE
Open_by_bme280の動作がおかしい

### ISSUE THREAD

**Issue by Kazu-hub** [core-rocket/amatsukaze#11]
![　](https://user-images.githubusercontent.com/56674535/69003848-4e0f2000-094c-11ea-96cb-62d2d62cc5fa.png)
Open_by_bme280を読み込んでArduino prominiとbme280で動作試験したところ、 高度を上げたときにOPENbyBME280_[SUCCESS]が出るはずが、特に動かさなくてもOPENbyBME280_[SUCCESS]と表示されました。また、OPENbyBME280_[SUCCESS]と表示された後も画像のように不定期でOPENbyBME280_[SUCCESS]と表示されます。

**Comment by Yukuro** [comment]
4ee256f にて修正
