### ISSUE TITLE
加速度センサによる離床判定

### ISSUE THREAD

**Issue by sksat** [core-rocket/amatsukaze#20]
# 概要
使用センサ: MPU6050
## 安全審査書の記述
加速度センサによって計測したデータのXYZ軸合成加速度の5回移動平均の値が5回連続で0.1s以内に3G以上(シミュレーション結果より)であることを検知

# ToDo
- [x] MPU6050の動作確認
- [x] XYZ軸合成加速度の取得
- [x] 5回移動平均処理
- [x] 判定の動作確認

**Comment by Yukuro** [comment]
da26599 にて実装(動作確認済)
