### ISSUE TITLE
頂点検知による開放判定

### ISSUE THREAD

**Issue by sksat** [core-rocket/amatsukaze#21]
# 概要
温湿度/気圧センサで頂点検知して開放判定

- 使用センサ: BME280
- サンプリングレート: 100Hz

## 安全審査書の記述
温湿度/気圧センサによって計測したデータから、発射後のロケットの高度を求め、
その高度の5回平均の値が5回連続で一つ前の値より小さいことを検知する。
尚、高度h [m]は気圧をP [hPa]、気温をT [℃]として以下式(1)で求めるものとする。

### 式(1)
<img src="https://latex.codecogs.com/gif.latex?h&space;=&space;\frac{(\frac{1013.25}{P}^\frac{1}{5.257}-1)(T+273.15)}{0.0065}">

**Comment by Yukuro** [comment]
4ee256f にて実装(テストコードにて動作確認済み)
- テストパラメータ
  - `OPEN_BY_BME280_LIMIT = 2`
  - `OPEN_BY_BME280_DIFF_RATE = 0.2`
