### ISSUE TITLE
GNSSがシリアル出力しない

### ISSUE THREAD

**Issue by Yukuro** [core-rocket/amatsukaze#23]
## 詳細
- 使用GNSSモジュール
  -  [AE-GNSS-EXTANT](http://akizukidenshi.com/catalog/g/gK-13850/)
<br>
- Arduino pro miniとGNSSモジュールの通信が出来ない
- PCとGNSSモジュールを直接FT232HL経由でUARTで開くと以下のように`<0xff>`が立て続けに表示される

```
<0xff><0xff><0xff><0xff><0xff><0xff><0xff><0xff>...
```

- 対応ボーレート範囲(4800~115200bps)で試したが、同じ表示だった
  - `4800`,`9600`,`19200`,`38400`,`57600`,`115200`

**Comment by Yukuro** [comment]
壊れている可能性大なので新しいモジュールを新たに購入する

**Comment by sksat** [comment]
予備はありますか？壊れやすいものなのであれば多めに購入しておいた方が良いかもしれません

**Comment by Yukuro** [comment]
予備もなければ予算もありません...(残り4000円ほど)

**Comment by sksat** [comment]
悲しい...

**Comment by sksat** [comment]
他にも予備が無い(けど壊れやすい)ものってありますか？

**Comment by Yukuro** [comment]
ES920LRがそうですが、過去のプロジェクトの余りがあるそうなので問題ないです

**Comment by sksat** [comment]
了解しました．

**Comment by sksat** [comment]
必要最低限の範囲内であれば予算超過してもよいとのことなので，優先順位の高いものから予備を買っていくかんじですかね．

**Comment by Yukuro** [comment]
新たに購入したモジュールで動作確認できたのでcloseします
