### ISSUE TITLE
センサ値取得部分のリファクタリング

### ISSUE THREAD

**Issue by sksat** [core-rocket/amatsukaze#24]
既にdevelopに諸々がマージされてしまったのでリファクタリングとします．

まず，全てのセンサの値を`void get_all_sensor_value()`で読み込むようになっていますが，これは適切でしょうか？
センサの値を読む部分とその評価(=判定)を行う部分を分離するのはよいと思います．
特に，今回のように生のセンサ値に対してソフトウェア上でフィルタをかける場合，値の評価よりも値の取得の方が頻度が高いからです．
ただ，気になるのが`get_all_sensor_value()`内では最新の生のデータを取得し，判定の部分でフィルタに値を追加している点です．
生の値を別の用途に用いるようなことが無いのであれば，値の取得時に`add_data()`してよいと思います(`add_data()`はリングバッファへの値の追加なのであまりコストはかかりません)．
グローバル変数も減らせます．

あと，細かいことですが加速度の定数・変数の単位をコメントで書くようにして下さい．
また，合成加速度をsqrtを使って計算していますが，sqrtはとても計算コストのかかる処理です．
結局やることは閾値との比較なので，閾値を指定値の2乗にしておくとsqrtを使わずに済みます．

次に，サンプリングレートについてですが，安全審査書の記述を見るとGNSSが1Hzでそれ以外が100Hzとなっています．
ですが，現状のコードではこれに従っていません．
GNSSの場合はUARTでNMEAを1byteずつパースしてパースが完了したら値を更新する，というようになっているので，
GNSSモジュールの設定が1Hzになっていればこれでもよい(とはいえ，isValidをチェックする間隔は1Hzでもよいでしょう)のですが，
他のセンサの値の取得は100Hzになっていません．

`loop()`の一番下で`deley(15)`となっていますが，[deleyで止まるのはms単位です](https://www.arduino.cc/reference/en/language/functions/time/delay/)．
さらに，微々たるものではあるでしょうが，`get_all_sensor_value()`から`deley(15)`までの間の処理時間もあるので，
実際に`get_all_sensor_value()`が呼ばれるのは15+α[ms]ごとになります．
センサの値の取得や合成加速度の計算にかかる時間を0と仮定しても，約66Hzです．
そしてこれは`loop()`全体の処理時間が一定であればの話です．

そのため，値の取得時に時間も取得するようにして，前回の取得時から10ms以上経過していれば値を更新，もしくは10-経過時間[ms]だけ待ってから値を取得，とするべきです(この2つであれば前者の方が処理をブロックせずに済みます)．タイマ割り込みでもいいですが，今回の場合Arduinoなのでちょっと微妙かもしれません．

**Comment by Yukuro** [comment]
>まず，全てのセンサの値をvoid get_all_sensor_value()で読み込むようになっていますが...
- 適切ではなかったので 33705fcc で修正しました

>あと，細かいことですが加速度の定数・変数の単位をコメントで書くようにして下さい．
- 3d3b1d6b にて修正しました

>また，合成加速度をsqrtを使って計算していますが...
- 03deccd3 にて修正しました

>そのため，値の取得時に時間も取得するようにして...
- 3b951c0b にて修正しました(前者の方法)
- が、Serial.println等で割と値取得時の時間が変わってくるので根本的解決ではないです
- MPU6050はセンサ内にFIFOバッファがあるので100Hzで取得した値を格納しておくみたいな事が可能なのですが、他のセンサはありません
  - Arduino pro mini内のRAM等を使えばよいのかもしれませんが、(自分の技術力的に)残り期間で実装するのは難しいです...

**Comment by sksat** [comment]
確認しました．まず，経過時間を使って一定のサンプリングレートを実現する場合，とにかく`loop()`を速く回す必要があるので，`delay(15)`は消さないと意味がないです．
https://github.com/core-rocket/amatsukaze/blob/develop/Avionics/src/main.cpp#L160

また，このような方法が根本的解決でないのは確かで，本来ならばタイマ割り込みを使うべきです．ですが，`SoftwareSerial`もPWMもi2cもタイマ割り込みを使っているので，Arduinoでは同時に使用する場合は注意が必要です．

MPU6050のDMPとFIFOは使うべきなので，余裕があれば実装するべきだと思います．

**Comment by Yukuro** [comment]
55632e4d にて修正しました

DMPとFIFOは全体が固まってから実装します

**Comment by sksat** [comment]
確認しました．
